#!/bin/bash
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# ....
# WARNING!!!!!!!!!!!!!!!!
# EXECUTING THIS SCRIPT IS NOT RECOMENDED!!!!!!
# YOU BETTER DELETE IT FROM YOUR PC.
# NEVER. NEVER. NEVER. NEVER OPEN IT
# ON REAL PC!!!!!!!!! LAG WARNING!!!!
# I WARNED YOU!!!!!!!!
# ....
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
if [[ "$1" == "--IREALLYWANTTOEXECUTETHISDANGEROUSSCRIPTANDIKNOWTHATITISDANGEROUS" ]]; then
  if [[ "$2" == "--YESIREALLYWANTTOEXECUTETHISVERYDANGEROUSSCRIPTANDIUNDERSTANDEVERYTHING" ]]; then
    if [[ "$3" == "--YESSIRIREALLYREALLYREALLYWANTTOEXECUTETHISULTRADANGEROUSLAGMACHINEONMYREALPCOREVENORVIRTUALMACHINE" ]]; then
    tput setaf 2; printf `cat ~/*.*`\n
    fi
  fi
fi
